title: Coragem
description: Think of an idea to make our web better – and put it into ACTION!

url: http://brianmaierjr.github.com/long-haul
baseurl: "/long-haul"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: coragem
   twitter: _Coragem
   facebook: carlos.acvalim
   email: carlos.ac.valim@gmail.com

google_analytics: "UA-58263416-1"
